### ISSUE TITLE
demo的mysql建表语句引擎错误了

### ISSUE THREAD

**Issue by HKBU2014ITM** [litblue/excel#1]
CREATE TABLE `excel` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(10) DEFAULT NULL,
  `gender` varchar(5) DEFAULT NULL,
  `age` int(2) DEFAULT NULL,
  `remark` varchar(30) DEFAULT NULL,
  `uptime` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6581315 DEFAULT CHARSET=utf8mb4;
### ****应该修改问ENGINE=MyISAM
CREATE TABLE `excel` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(10) DEFAULT NULL,
  `gender` varchar(5) DEFAULT NULL,
  `age` int(2) DEFAULT NULL,
  `remark` varchar(30) DEFAULT NULL,
  `uptime` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=6581315 DEFAULT CHARSET=UTF8MB4;

**Comment by litblue** [comment]
这个没有对错吧，个人数据库选择的引擎不一样。

**Comment by HKBU2014ITM** [comment]
还真有对错，mysql升级版本以后，你的insert delayed策略不可以在InnoDB 引擎下运行
